# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumdireito_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='T\xedtulo')),
                ('curriculo', models.TextField(blank=True, max_length=140, null=True, verbose_name='Mini curr\xedculo')),
                ('dt_abertura', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='palestras',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forumdireito_app.Palestrante'),
        ),
    ]
