# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumdireito_app', '0002_auto_20180516_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestras',
            old_name='usuario',
            new_name='palestrante',
        ),
    ]
