# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumdireito_app', '0005_auto_20180522_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPF')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('pergunta', models.TextField(blank=True, max_length=140, null=True, verbose_name='Pergunta')),
                ('dt_pergunta', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
    ]
