# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumdireito_app', '0006_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='status',
            field=models.TextField(blank=True, choices=[('0', 'Aguardando Resposta'), ('2', 'Respondido'), ('3', 'Cancelado')], max_length=140, null=True, verbose_name='Pergunta'),
        ),
    ]
